@echo off
setlocal EnableExtensions EnableDelayedExpansion

REM === Win-ACME + Nginx HTTPS Setup (Windows VPS) ===
REM What this does:
REM - Ensures nginx includes conf.d\*.conf (non-destructive, creates nginx.conf.bak once)
REM - Creates an ACME webroot folder for http-01 challenges
REM - Writes an nginx vhost for HTTP (challenge + redirect) + HTTPS (reverse proxy)
REM - Downloads win-acme (wacs.exe) and requests a Let's Encrypt cert
REM - Exports cert/key as PEM files for nginx and reloads nginx
REM - Configures win-acme to reload nginx after renewals (script installation plugin)
REM
REM Requirements:
REM - Run as Administrator
REM - DNS A/AAAA for DOMAIN points to this VPS
REM - Inbound ports 80 and 443 are reachable from the internet
REM - Nginx for Windows is installed (this script configures it; it doesn't install it)

title Win-ACME + Nginx HTTPS Setup

REM Step-based progress bar (not time-based).
set "TOTAL_STEPS=9"
set "STEP=0"
call :progress "Starting..."

REM ====== CONFIG (EDIT THESE) ======
set "DOMAIN=adhan-bot.online"
set "UPSTREAM=http://127.0.0.1:3010"
set "EMAIL=you@example.com"

REM Path to your nginx folder (must contain nginx.exe and conf\nginx.conf)
set "NGINX_DIR=C:\nginx"

REM win-acme install dir (recommended non-temporary path)
set "WACS_DIR=%ProgramFiles%\win-acme"

REM Download URL for win-acme trimmed x64 (official GitHub release)
REM Source: chocolatey verification points to this release artifact
set "WACS_ZIP_URL=https://github.com/win-acme/win-acme/releases/download/v2.2.9.1701/win-acme.v2.2.9.1701.x64.trimmed.zip"

REM Include www in the certificate + nginx server_name? (requires DNS for www to point here)
set "INCLUDE_WWW=0"
REM =================================

REM Admin check
call :progress "Checking Administrator permissions..."
net session >nul 2>&1
if not "%errorlevel%"=="0" (
  echo ERROR: Run this as Administrator.
  call :done_pause
  exit /b 1
)

REM Validate nginx paths
call :progress "Validating nginx installation paths..."
if not exist "%NGINX_DIR%\nginx.exe" (
  echo ERROR: nginx.exe not found at "%NGINX_DIR%\nginx.exe"
  call :done_pause
  exit /b 2
)
if not exist "%NGINX_DIR%\conf\nginx.conf" (
  echo ERROR: nginx.conf not found at "%NGINX_DIR%\conf\nginx.conf"
  call :done_pause
  exit /b 3
)

REM Open firewall ports (idempotent)
call :progress "Opening Windows Firewall for ports 80/443..."
echo Opening Windows Firewall ports 80/443 (if not already open)...
netsh advfirewall firewall add rule name="Nginx HTTP (80)" dir=in action=allow protocol=TCP localport=80 >nul 2>&1
netsh advfirewall firewall add rule name="Nginx HTTPS (443)" dir=in action=allow protocol=TCP localport=443 >nul 2>&1

REM Create folders
call :progress "Creating ACME webroot and SSL folders..."
set "CONF_D_DIR=%NGINX_DIR%\conf\conf.d"
set "WEBROOT=%NGINX_DIR%\acme-webroot"
set "CHALLENGE_DIR=%WEBROOT%\.well-known\acme-challenge"
set "SSL_DIR=%NGINX_DIR%\ssl\%DOMAIN%"

if not exist "%CONF_D_DIR%" mkdir "%CONF_D_DIR%" >nul
if not exist "%CHALLENGE_DIR%" mkdir "%CHALLENGE_DIR%" >nul
if not exist "%SSL_DIR%" mkdir "%SSL_DIR%" >nul

REM Make sure nginx.conf includes conf.d/*.conf inside the http {} block
call :progress "Ensuring nginx.conf includes conf.d\\*.conf..."
echo Ensuring nginx includes conf.d\*.conf ...
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$nginxConf = Join-Path '%NGINX_DIR%' 'conf\\nginx.conf';" ^
  "$includeLine = '    include conf.d/*.conf;';" ^
  "$text = Get-Content -Raw -Path $nginxConf;" ^
  "if ($text -match [regex]::Escape($includeLine)) { exit 0 }" ^
  "$bak = $nginxConf + '.bak'; if (-not (Test-Path $bak)) { Copy-Item -Force $nginxConf $bak }" ^
  "$lines = Get-Content -Path $nginxConf;" ^
  "$out = New-Object System.Collections.Generic.List[string];" ^
  "$inserted = $false;" ^
  "for ($i=0; $i -lt $lines.Length; $i++) {" ^
  "  $out.Add($lines[$i]);" ^
  "  if (-not $inserted -and $lines[$i] -match '^[\\s]*http[\\s]*\\{[\\s]*$') {" ^
  "    $out.Add($includeLine);" ^
  "    $inserted = $true;" ^
  "  }" ^
  "}" ^
  "if (-not $inserted) { Write-Host 'ERROR: Could not find http { block in nginx.conf'; exit 2 }" ^
  "[IO.File]::WriteAllLines($nginxConf, $out)"
if "%errorlevel%"=="2" (
  echo ERROR: Failed to patch nginx.conf (could not find http { block).
  call :done_pause
  exit /b 4
)

REM Write nginx vhost
call :progress "Writing nginx site config (HTTP first)..."
set "VHOST=%CONF_D_DIR%\%DOMAIN%.conf"
set "VHOST_TMP=%CONF_D_DIR%\%DOMAIN%.tmp.conf"
set "RELOAD_SCRIPT=%NGINX_DIR%\reload-nginx.bat"

REM Build server_name list
set "SERVER_NAMES=%DOMAIN%"
if "%INCLUDE_WWW%"=="1" set "SERVER_NAMES=%DOMAIN% www.%DOMAIN%"

REM Convert upstream to host:port for nginx proxy_pass
REM UPSTREAM is expected like http://127.0.0.1:3010
for /f "tokens=1,2 delims=:" %%a in ("%UPSTREAM%") do (
  REM no-op, just validating basic structure
)

echo Writing nginx vhost to "%VHOST%" ...
(
  echo # Auto-generated by setup-winacme-nginx-https.bat
  echo # Domain: %DOMAIN%
  echo
  echo server {
  echo   listen 80;
  echo   server_name %SERVER_NAMES%;
  echo
  echo   # ACME http-01 challenge files (win-acme writes under the webroot)
  echo   location ^~ /.well-known/acme-challenge/ {
  echo     root %WEBROOT:\=/%;
  echo     default_type text/plain;
  echo     try_files $uri =404;
  echo   }
  echo
  echo   location / {
  echo     return 301 https://$host$request_uri;
  echo   }
  echo }
  echo
  echo server {
  echo   listen 443 ssl http2;
  echo   server_name %SERVER_NAMES%;
  echo
  echo   ssl_certificate     %SSL_DIR:\=/%/%DOMAIN%-chain.pem;
  echo   ssl_certificate_key %SSL_DIR:\=/%/%DOMAIN%-key.pem;
  echo   ssl_protocols TLSv1.2 TLSv1.3;
  echo
  echo   # Basic hardening headers
  echo   add_header X-Content-Type-Options "nosniff" always;
  echo   add_header Referrer-Policy "no-referrer" always;
  echo   add_header Permissions-Policy "interest-cohort=()" always;
  echo
  echo   # Reverse proxy to your Node dashboard
  echo   location / {
  echo     proxy_pass %UPSTREAM%;
  echo     proxy_http_version 1.1;
  echo     proxy_set_header Host $host;
  echo     proxy_set_header X-Real-IP $remote_addr;
  echo     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  echo     proxy_set_header X-Forwarded-Proto $scheme;
  echo     proxy_set_header Upgrade $http_upgrade;
  echo     proxy_set_header Connection "upgrade";
  echo   }
  echo }
) > "%VHOST_TMP%"

REM If cert files don't exist yet, nginx -t would fail.
REM So we start with a HTTP-only vhost first (no ssl directives), get cert, then swap to full config.
echo Writing temporary HTTP-only vhost...
(
  echo # Temporary HTTP-only config for initial ACME validation
  echo server {
  echo   listen 80;
  echo   server_name %SERVER_NAMES%;
  echo
  echo   location ^~ /.well-known/acme-challenge/ {
  echo     root %WEBROOT:\=/%;
  echo     default_type text/plain;
  echo     try_files $uri =404;
  echo   }
  echo
  echo   location / {
  echo     proxy_pass %UPSTREAM%;
  echo     proxy_http_version 1.1;
  echo     proxy_set_header Host $host;
  echo     proxy_set_header X-Real-IP $remote_addr;
  echo     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  echo     proxy_set_header X-Forwarded-Proto $scheme;
  echo   }
  echo }
) > "%VHOST%"

REM Write reload script for win-acme renewals
call :progress "Writing nginx reload hook for renewals..."
echo Writing nginx reload script to "%RELOAD_SCRIPT%" ...
(
  echo @echo off
  echo "%NGINX_DIR%\nginx.exe" -t 1^>nul 2^>^&1
  echo if not "%%errorlevel%%"=="0" exit /b 1
  echo "%NGINX_DIR%\nginx.exe" -s reload
) > "%RELOAD_SCRIPT%"

REM Start or reload nginx
call :progress "Testing + starting/reloading nginx..."
echo Testing nginx config...
"%NGINX_DIR%\nginx.exe" -t
if not "%errorlevel%"=="0" (
  echo ERROR: nginx config test failed. Fix nginx.conf / conf.d config and rerun.
  call :done_pause
  exit /b 5
)

tasklist /FI "IMAGENAME eq nginx.exe" | findstr /I "nginx.exe" >nul
if "%errorlevel%"=="0" (
  echo Reloading nginx...
  "%NGINX_DIR%\nginx.exe" -s reload
) else (
  echo Starting nginx...
  "%NGINX_DIR%\nginx.exe"
)

REM Install win-acme
call :progress "Installing win-acme (wacs.exe) if needed..."
if not exist "%WACS_DIR%\wacs.exe" (
  echo Downloading win-acme...
  if not exist "%WACS_DIR%" mkdir "%WACS_DIR%" >nul
  set "WACS_ZIP=%TEMP%\win-acme.zip"
  curl.exe -fsSL -o "%WACS_ZIP%" "%WACS_ZIP_URL%"
  if not "%errorlevel%"=="0" (
    echo ERROR: Failed to download win-acme from:
    echo   %WACS_ZIP_URL%
    call :done_pause
    exit /b 6
  )
  echo Extracting win-acme to "%WACS_DIR%" ...
  powershell -NoProfile -ExecutionPolicy Bypass -Command ^
    "Expand-Archive -Force -Path '%WACS_ZIP%' -DestinationPath '%WACS_DIR%'; Remove-Item -Force '%WACS_ZIP%'"
  if not exist "%WACS_DIR%\wacs.exe" (
    echo ERROR: wacs.exe not found after extraction.
    call :done_pause
    exit /b 7
  )
)

REM Request certificate (PEM files for nginx) and configure renewal to reload nginx
call :progress "Requesting Let's Encrypt certificate via win-acme..."
echo Requesting/renewing certificate for %SERVER_NAMES% ...
set "HOST_ARG=%DOMAIN%"
if "%INCLUDE_WWW%"=="1" set "HOST_ARG=%DOMAIN%,www.%DOMAIN%"

"%WACS_DIR%\wacs.exe" ^
  --accepttos ^
  --emailaddress "%EMAIL%" ^
  --source manual ^
  --host "%HOST_ARG%" ^
  --validation filesystem ^
  --webroot "%WEBROOT%" ^
  --store pemfiles ^
  --pemfilespath "%SSL_DIR%" ^
  --pemfilesname "%DOMAIN%" ^
  --installation script ^
  --script "%RELOAD_SCRIPT%" ^
  --scriptparameters "" ^
  --verbose

if not "%errorlevel%"=="0" (
  echo ERROR: win-acme failed. Check that:
  echo - DNS for %DOMAIN% points to this VPS
  echo - Port 80 is reachable externally
  echo - http://%DOMAIN%/.well-known/acme-challenge/test works (served by nginx)
  call :done_pause
  exit /b 8
)

REM Switch to full HTTPS config (now that cert files exist), then reload
call :progress "Enabling HTTPS config and reloading nginx..."
echo Enabling HTTPS vhost and reloading nginx...
copy /Y "%VHOST_TMP%" "%VHOST%" >nul
del /Q "%VHOST_TMP%" >nul 2>&1

"%NGINX_DIR%\nginx.exe" -t
if not "%errorlevel%"=="0" (
  echo ERROR: nginx config test failed after enabling HTTPS. Check cert paths and rerun.
  call :done_pause
  exit /b 9
)
call "%RELOAD_SCRIPT%"

echo.
echo DONE.
echo - Nginx vhost: %VHOST%
echo - ACME webroot: %WEBROOT%
echo - Cert files: %SSL_DIR%
echo.
echo Next steps for your dashboard:
echo - Set WEB_BASE_URL=https://%DOMAIN% in your .env and restart the Node app
echo - Add https://%DOMAIN%/auth/callback to Discord OAuth Redirect URLs (and Auth0 if you're using it)
echo.
call :done_pause
exit /b 0

REM === helpers ===
:progress
set /a STEP+=1
if %STEP% gtr %TOTAL_STEPS% set "STEP=%TOTAL_STEPS%"
set "MSG=%~1"
call :render_bar %STEP% %TOTAL_STEPS% "%MSG%"
exit /b 0

:render_bar
set "CUR=%~1"
set "TOT=%~2"
set "MSG=%~3"
set /a PCT=CUR*100/TOT
set /a WIDTH=28
set /a FILLED=CUR*WIDTH/TOT
set "BAR="
for /l %%i in (1,1,%WIDTH%) do (
  if %%i leq !FILLED! (set "BAR=!BAR!#") else (set "BAR=!BAR!-")
)
echo [!BAR!] !PCT!%%  (!CUR!/!TOT!)  !MSG!
exit /b 0

:done_pause
echo.
echo Press any key to close this window...
pause >nul
exit /b 0
